  
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const AGREGAR_TAREA_EXITO = 'AGREGAR_TAREA_EXITO';
export const AGREGAR_TAREA_ERROR = 'AGREGAR_TAREA_ERROR';

export const COMENZAR_DESCARGA_TAREAS = 'COMENZAR_DESCARGA_TAREAS';
export const DESCARGA_TAREAS_EXITO = 'DESCARGA_TAREAS_EXITO';
export const DESCARGA_TAREAS_ERROR = 'DESCARGA_TAREAS_ERROR';

export const OBTENER_TAREA_ELIMINAR = 'OBTENER_TAREA_ELIMINAR';
export const TAREA_ELIMINADA_EXITO = 'TAREA_ELIMINADA_EXITO';
export const TAREA_ELIMINADA_ERROR = 'TAREA_ELIMINADA_ERROR';

export const OBTENER_TAREA_EDITAR = 'OBTENER_TAREA_EDITAR';
export const COMENZAR_EDICION_TAREA = 'COMENZAR_EDICION_TAREA';
export const TAREA_EDITADA_EXITO = 'TAREA_EDITADA_EXITO';
export const TAREA_EDITADA_ERROR = 'TAREA_EDITADA_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';